abstract class AppState {}
class InitialAppState extends AppState{}
class ChangePgaeViewAppState extends AppState{}
class ChangeDotIndicatorAppState extends AppState{}
class SelcetedItemAppState extends AppState{} 
class ChangeButtonItemAppState extends AppState{} 
class NextQuestionAppState extends AppState{} 
class ResetTimerAppState extends AppState{} 
class FinishQuestionAppState extends AppState{} 
